# Additional topics 

- handling variable length sequence
    - while building your model there can be cases when model may encounter varaible-length sequeses
    - sequence 1 [32,45,78,98] length =4
    - sequence 2 [1,8]         length =2
 
- pad_sequences - keras provides a method for above


In [1]:
from keras_preprocessing.sequence import pad_sequences

In [2]:
#create dummy sequences stored in a python list
seq=[[11, 6], [2, 5, 1], [1, 8, 7, 6, 9]]
#adds padding to the beginning of the sequence
pad_sequences(seq,padding='pre')

array([[ 0,  0,  0, 11,  6],
       [ 0,  0,  2,  5,  1],
       [ 1,  8,  7,  6,  9]])

In [3]:
# adds padding to the end of the sequence 
pad_sequences(seq,padding='post')

array([[11,  6,  0,  0,  0],
       [ 2,  5,  1,  0,  0],
       [ 1,  8,  7,  6,  9]])

# max length padding 

In [4]:
pad_sequences(seq,maxlen=7,padding='post')

array([[11,  6,  0,  0,  0,  0,  0],
       [ 2,  5,  1,  0,  0,  0,  0],
       [ 1,  8,  7,  6,  9,  0,  0]])

In [5]:
pad_sequences(seq,maxlen=3,padding='pre')

array([[ 0, 11,  6],
       [ 2,  5,  1],
       [ 7,  6,  9]])

# Fetching Hidden and cell states of an LSTM Cell
    - we can fetch the output value of the previous timestamp from the hidden layer using return_sequences 
    - this way we not only have the output of the final timestamp but also the subsequent timestamp outputs

In [6]:
from keras.models import Model
from keras.layers import Input, LSTM
import numpy as np

In [7]:
inputs = np.array([0.2, 0.3, 0.4, 0.5, 0.6]).reshape((1, 5, 1))
print(inputs)

[[[0.2]
  [0.3]
  [0.4]
  [0.5]
  [0.6]]]


In [ ]:
#define random LSTM network
np.random.seed(42)
feed = Input(shape=(5,1))
lstm, state_h, state_c,= LSTM(1, return_sequences=True,return_state=True)(feed)
model = Model(inputs=feed,outputs=(lstm,state_h,state_c))

#Predictions
print('Outputs from each five timestamps')
model.predict(inputs)

Outputs from each five timestamps


In [23]:
model.add(Dropout(0.3))

AttributeError: 'Functional' object has no attribute 'add'

# Dropout
    - however if we try to use dropout for RNN(LSTM/GRU) it can interfere with the timestamps unless you rely on its arguments noise_shape
    - since it take 2 inputs (output of previous state and current input)
    - therefore its not always necessary that the output from the previous state may match the dimension of the current input. 
    - droupout :- Current input
    - recurrent_dropout :- Recurrent state(previous output and/or cell state)
    - both take values between 0 and 1 